
spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
  profiles:
    default: local

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # 하이버네이트 버전업으로 인한 바인딩 출력 옵션 변경
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      base-path: /management
      path-mapping:
        health: health_check
        exposure:
            include: "*"
---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: update # create update none

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/react_board?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: jisu
    password: 1111
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

# JWT
jwt:
  secret-key: com.example.kim_ji_su.application-2023.secret_key
  #30 days
  token-expired-time-ms: 2592000000

---

spring.config.activate.on-profile: dev

spring:
  config:
    import: db.yml

# JWT
jwt:
  secret-key: com.example.kim_ji_su.application-2023.secret_key
  #30 days
  token-expired-time-ms: 2592000000
